version: '3'
services:
    database:
        container_name: mysql
        image: mysql
        ports:
            - "3300:3300"
        restart: always
  
        environment:
            MYSQL_ROOT_USER: root
            MYSQL_USER: root
            MYSQL_PASSWORD: 12345
            MYSQL_ROOT_PASSWORD: 12345
            MYSQL_DATABASE: olshop