version: '3'
services:
    db:
        container_name: mysql
        image: mysql
        ports:
            - "3300:3306"
        restart: always
  
        environment:
            MYSQL_USER: u123
            MYSQL_PASSWORD: u1234
            MYSQL_ROOT_PASSWORD: u1234
            MYSQL_DATABASE: olshop