// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	transaction "graphql/transaction"

	mock "github.com/stretchr/testify/mock"
)

// ServiceTransInt is an autogenerated mock type for the ServiceTransInt type
type ServiceTransInt struct {
	mock.Mock
}

// CreateTransaction provides a mock function with given fields: idProduct, customerID, quantity
func (_m *ServiceTransInt) CreateTransaction(idProduct int, customerID int, quantity int) (transaction.Transactions, error) {
	ret := _m.Called(idProduct, customerID, quantity)

	var r0 transaction.Transactions
	if rf, ok := ret.Get(0).(func(int, int, int) transaction.Transactions); ok {
		r0 = rf(idProduct, customerID, quantity)
	} else {
		r0 = ret.Get(0).(transaction.Transactions)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int, int, int) error); ok {
		r1 = rf(idProduct, customerID, quantity)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
